"""
build_dart_robot_showcase_SPEC.py
=================================
Assemble a single visual HTML demo page from per-stage manifests.

This script does not run physics or simulation logic. It only consumes
artifacts generated by validation scripts.

Run:
  python build_dart_robot_showcase_SPEC.py
"""

from __future__ import annotations

import json
from html import escape
from pathlib import Path

from dartrobot.paths import artifacts_dir_SPEC

ARTIFACTS = artifacts_dir_SPEC()

MANIFESTS = [
    ARTIFACTS / "flight" / "flight_demo_manifest_SPEC.json",
    ARTIFACTS / "motion" / "motion_demo_manifest_SPEC.json",
    ARTIFACTS / "integration" / "integration_demo_manifest_SPEC.json",
]


def _fmt_metric(value: object) -> str:
    if isinstance(value, float):
        return f"{value:.4f}"
    if isinstance(value, list):
        # Keep small vectors readable in callouts.
        if value and all(isinstance(v, (int, float)) for v in value):
            return "[" + ", ".join(f"{float(v):.4f}" for v in value) + "]"
        return json.dumps(value)
    return str(value)


def _media_tag(path: Path, caption: str) -> str:
    suffix = path.suffix.lower()
    rel = path.relative_to(ARTIFACTS) if path.is_absolute() and path.is_relative_to(ARTIFACTS) else path
    src = escape(str(rel))
    cap = escape(caption)
    if suffix in {".png", ".jpg", ".jpeg", ".gif", ".webp"}:
        return f'<figure><img src="{src}" alt="{cap}"><figcaption>{cap}</figcaption></figure>'
    if suffix in {".mp4", ".webm", ".mov"}:
        return (
            f'<figure><video controls preload="metadata"><source src="{src}"></video>'
            f"<figcaption>{cap}</figcaption></figure>"
        )
    return f'<p><a href="{src}">{cap}</a></p>'


def _stage_block(stage_manifest: dict) -> str:
    stage = escape(str(stage_manifest.get("stage", "unknown_stage")))
    metrics = stage_manifest.get("metrics", {})
    artifacts = stage_manifest.get("artifacts", [])
    metric_items = "\n".join(
        f"<li><strong>{escape(str(k))}</strong>: {escape(_fmt_metric(v))}</li>"
        for k, v in metrics.items()
    )
    media_html = []
    for item in artifacts:
        p = Path(item.get("path", ""))
        cap = item.get("caption", p.name)
        media_html.append(_media_tag(p, cap))
    return f"""
    <section class="stage">
      <h2>{stage}</h2>
      <div class="row">
        <div class="card">
          <h3>Key Metrics</h3>
          <ul>{metric_items}</ul>
        </div>
      </div>
      <div class="media-grid">
        {''.join(media_html)}
      </div>
    </section>
    """


def _missing_block(missing: list[Path]) -> str:
    if not missing:
        return ""
    lis = "".join(f"<li>{escape(str(p.name))}</li>" for p in missing)
    return f"""
    <section class="warning">
      <h2>Missing manifests</h2>
      <p>Run the demo validations first to generate these files:</p>
      <ul>{lis}</ul>
    </section>
    """


def main() -> None:
    ARTIFACTS.mkdir(parents=True, exist_ok=True)
    loaded = []
    missing = []
    for path in MANIFESTS:
        if not path.exists():
            missing.append(path)
            continue
        loaded.append(json.loads(path.read_text(encoding="utf-8")))

    sections = "\n".join(_stage_block(m) for m in loaded)
    html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Dart Robot Visual Demo</title>
  <style>
    body {{
      margin: 0;
      font-family: "Segoe UI", Tahoma, sans-serif;
      background: #0f172a;
      color: #e2e8f0;
    }}
    main {{
      max-width: 1100px;
      margin: 0 auto;
      padding: 28px 20px 40px;
    }}
    h1 {{
      margin: 0 0 8px;
      font-size: 2rem;
    }}
    p.lead {{
      margin: 0 0 24px;
      color: #a5b4fc;
    }}
    section.stage, section.warning {{
      background: #111827;
      border: 1px solid #334155;
      border-radius: 12px;
      padding: 16px;
      margin-bottom: 18px;
    }}
    .row {{
      display: grid;
      grid-template-columns: 1fr;
      gap: 12px;
      margin-bottom: 12px;
    }}
    .card {{
      background: #1e293b;
      border-radius: 10px;
      padding: 12px;
    }}
    .card ul {{
      margin: 8px 0 0;
      padding-left: 18px;
    }}
    .media-grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
      gap: 12px;
    }}
    figure {{
      margin: 0;
      background: #020617;
      border: 1px solid #334155;
      border-radius: 10px;
      padding: 8px;
    }}
    img, video {{
      width: 100%;
      display: block;
      border-radius: 6px;
      background: #000;
    }}
    figcaption {{
      margin-top: 6px;
      color: #cbd5e1;
      font-size: 0.92rem;
    }}
  </style>
</head>
<body>
  <main>
    <h1>Dart Robot Visual Demo</h1>
    <p class="lead">Trajectory, arm motion, and Monte Carlo behavior in one view.</p>
    {_missing_block(missing)}
    {sections}
  </main>
</body>
</html>
"""
    out_path = ARTIFACTS / "demo" / "dart_robot_visual_demo_SPEC.html"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(html, encoding="utf-8")
    print(f"Saved: {out_path}")

    summary_path = ARTIFACTS / "demo" / "demo_showcase_manifest_SPEC.json"
    summary = {
        "showcase_html": str(out_path),
        "loaded_stages": [m.get("stage", "unknown_stage") for m in loaded],
        "missing_manifests": [str(p) for p in missing],
    }
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(f"Saved: {summary_path}")


if __name__ == "__main__":
    main()

